# koyeb.yml - Web Service manifest (supports scale-to-zero)
app:
  name: txt-voice-bot
  region: global

services:
  - name: bot-web
    type: web
    build:
      dockerfile: Dockerfile
      context: .
    # Expose port used by your container
    ports:
      - name: http
        port: 8080

    # ROUTES: at least one HTTP route is required for services to be eligible to scale-to-zero.
    # If you omit "domain", Koyeb will create a default *.koyeb.app domain for the app+service.
    routes:
      - path: "/"
        # Optional: specify a custom domain here if you have one:
        # domain: "bots.example.com"

    env:
      - name: BOT_TOKEN
        value: "{{ secret.BOT_TOKEN }}"

    health_check:
      type: http
      path: "/"
      port: 8080
      interval_seconds: 30
      timeout_seconds: 5
      healthy_threshold: 2
      unhealthy_threshold: 3

    resources:
      cpu: 1
      memory: 512

    # Allow scaling down to zero when idle
    scaling:
      min: 0
      max: 1
